idf_component_register(SRCS "src/sensor_service.c"
                            "src/board.c"
                            "src/main.c"
                            "src/ext_probe.c"
                            "src/sensor_bus.c"
                            "src/sensor_service.c"
                       INCLUDE_DIRS "include")
